/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Fri Aug 23 16:39:42 KST 2024 ----! */
/* !---- Java-Unit: [pkg testfunction, cls TestFunction], gensrc/java/testfunction/TestFunction.java ----! */

package testfunction;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import java.nio.*;
import com.jogamp.common.util.*;
import java.util.Set;
import java.util.Map;
import java.util.HashMap;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;

public class TestFunction {


  /** Interface to C language function: <br> <code>int one_plus(int a)</code><br>   */
  public static native int one_plus(int a);

} // end of class TestFunction
