/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Fri Aug 23 16:55:20 KST 2024 ----! */
/* !---- Java-Unit: [pkg testfunction, cls TestFunction], output/gensrc/java/testfunction/TestFunction.java ----! */

package testfunction;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import java.nio.*;
import com.jogamp.common.util.*;
import java.util.Set;
import java.util.Map;
import java.util.HashMap;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;

public class TestFunction {


  /** Interface to C language function: <br> <code>float process_data(float *  data, int n)</code><br>
      @param data a direct or array-backed {@link java.nio.FloatBuffer}   */
  public static float process_data(FloatBuffer data, int n)  {

    final boolean data_is_direct = Buffers.isDirect(data);
        return process_data1(data_is_direct ? data : Buffers.getArray(data), data_is_direct ? Buffers.getDirectBufferByteOffset(data) : Buffers.getIndirectBufferByteOffset(data), data_is_direct, n);
  }

  /** Entry point to C language function: <code>float process_data(float *  data, int n)</code><br>
      @param data a direct or array-backed {@link java.nio.FloatBuffer}   */
  private static native float process_data1(Object data, int data_byte_offset, boolean data_is_direct, int n);

  /** Interface to C language function: <br> <code>float process_data(float *  data, int n)</code><br>   */
  public static float process_data(float[] data, int data_offset, int n)  {

    if(data != null && data.length <= data_offset)
      throw new RuntimeException("array offset argument \"data_offset\" (" + data_offset + ") equals or exceeds array length (" + data.length + ")");
        return process_data1(data, Buffers.SIZEOF_FLOAT * data_offset, false, n);
  }

  /** Interface to C language function: <br> <code>void set_global_data(float *  data)</code><br>
      @param data a direct only {@link java.nio.FloatBuffer}   */
  public static void set_global_data(FloatBuffer data)  {

    if (!Buffers.isDirect(data))
      throw new RuntimeException("Argument \"data\" is not a direct buffer");
    set_global_data0(data, Buffers.getDirectBufferByteOffset(data));
  }

  /** Entry point to C language function: <code>void set_global_data(float *  data)</code><br>
      @param data a direct only {@link java.nio.FloatBuffer}   */
  private static native void set_global_data0(Object data, int data_byte_offset);

  /** Interface to C language function: <br> <code>float process_global_data(int n)</code><br>   */
  public static native float process_global_data(int n);

} // end of class TestFunction
