/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Fri Aug 23 16:55:20 KST 2024 ----! */
/* !---- C-Unit: TestFunction_JNI.c, output/gensrc/native/TestFunction_JNI.c ----! */

#include <jni.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <stddef.h>

JavaVM* JVMUtil_GetJavaVM();
JNIEnv* JVMUtil_GetJNIEnv(int asDaemon, int* jvmAttached);
void JVMUtil_ReleaseJNIEnv(JNIEnv* env, int detachJVM);


static jobject JVMUtil_NewDirectByteBufferCopy(JNIEnv *env, jclass clazzBuffers, void * source_address, size_t capacity); /* forward decl. */

 #include "function.h"

/*   Java->C glue code:
 *   Java package: testfunction.TestFunction
 *    Java method: float process_data(java.nio.FloatBuffer data, int n)
 *     C function: float process_data(float *  data, int n)
 */
JNIEXPORT jfloat JNICALL 
Java_testfunction_TestFunction_process_1data1__Ljava_lang_Object_2IZI(JNIEnv *env, jclass _unused, jobject data, jint data_byte_offset, jboolean data_is_nio, jint n) {
  float * _data_ptr = NULL;
  float _res;
  if ( NULL != data ) {
    _data_ptr = (float *) ( JNI_TRUE == data_is_nio ?  (*env)->GetDirectBufferAddress(env, data) :  (*env)->GetPrimitiveArrayCritical(env, data, NULL) );  }
  _res = (float) process_data((float * ) (((char *) _data_ptr) + data_byte_offset), (int) n);
  if ( JNI_FALSE == data_is_nio && NULL != data ) {
    (*env)->ReleasePrimitiveArrayCritical(env, data, _data_ptr, 0);  }
  jfloat _res_jni = _res;
  return _res_jni;
}


/*   Java->C glue code:
 *   Java package: testfunction.TestFunction
 *    Java method: void set_global_data(java.nio.FloatBuffer data)
 *     C function: void set_global_data(float *  data)
 */
JNIEXPORT void JNICALL 
Java_testfunction_TestFunction_set_1global_1data0__Ljava_lang_Object_2I(JNIEnv *env, jclass _unused, jobject data, jint data_byte_offset) {
  float * _data_ptr = NULL;
    if ( NULL != data ) {
        _data_ptr = (float *) (((char*) (*env)->GetDirectBufferAddress(env, data)) + data_byte_offset);
    }

  set_global_data((float * ) _data_ptr);
}


/*   Java->C glue code:
 *   Java package: testfunction.TestFunction
 *    Java method: float process_global_data(int n)
 *     C function: float process_global_data(int n)
 */
JNIEXPORT jfloat JNICALL 
Java_testfunction_TestFunction_process_1global_1data__I(JNIEnv *env, jclass _unused, jint n) {
  float _res;
  _res = (float) process_global_data((int) n);
  jfloat _res_jni = _res;
  return _res_jni;
}


